<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class PERSON extends Model
{
    protected $table = 'PERSON';

    public $timestamps = false;

    use HasFactory;

    protected $primaryKey = 'PERSON_ID';

    protected $fillable = [
        'PERSON_ID',
        'APP_ID',
        'PRODUCT_ID',
        'CIF_PERSON_ID',
        'JURISTIC_ID',
        'FLAG_GUARANTOR',
        'PREFIX',
        'PREFIX_ENG',
        'PREFIX_OTHER',
        'FIRST_NAME',
        'FIRST_NAME_ENG',
        'LAST_NAME',
        'LAST_NAME_ENG',
        'CARD_CODE',
        'TAX_ID',
        'STUDENT_ID',
        'BIRTHDAY',
        'AGE',
        'CUSTOMER_TYPE',
        'SEX',
        'IDCARD_REGIS_DATE',
        'IDCARD_EXPIRE_DATE',
        'IDCARD_REGIS_BY',
        'NATIONALITY_CODE',
        'CITIZEN_CODE',
        'MARITAL_STATUS',
        'NUMBER_CHILDREN',
        'STUDY_CHILD',
        'PHONE',
        'EMAIL',
        'LINEID',
        'FACEBOOK',
        'OCCUPATION_CODE',
        'OCCUPATION_TYPE_CODE',
        'BUSINESSTYPE_CODE',
        'OCCUPATION_CODE_OTHER',
        'UNIVERSITY_PROVINCE',
        'UNIVERSITY_DISTRICT',
        'UNIVERSITY_NAME',
        'UNIVERSITY_OTHER',
        'CAMPUS_NAME',
        'FACULTY_NAME',
        'FACULTY_OTHER',
        'SUBJECT',
        'LEVEL_TYPE',
        'U_LEVEL',
        'LOAN_KYS',
        'OFFICE_NAME',
        'BUSINESS_TYPE',
        'OFFICE_POSITION',
        'OFFICE_LEVEL',
        'OFFICE_YEAR',
        'OFFICE_MONTH',
        'OFFICE_PHONE',
        'OFFICE_PHONE_EXTEN',
        'INCOME_TYPE',
        'MAIN_INCOME',
        'EXPENSE',
        'OTHER_INCOME',
        'AMOUNT_INCOME',
        'SOURCE_INCOME',
        'SOURCE_OTHER_INCOME',
        'SPOUSE_TITLE',
        'SPOUSE_FIRSTNAME',
        'SPOUSE_LASTNAME',
        'SPOUSE_OCCUPATION',
        'SPOUSE_OFFICE_NAME',
        'SPOUSE_BUSINESS_SIZE',
        'SPOUSE_OFFICE_POSITION',
        'SPOUSE_OFFICE_LEVEL',
        'SPOUSE_OFFICE_YEAR',
        'SPOUSE_MAIN_INCOME',
        'SPOUSE_EXPENSE',
        'SPOUSE_OTHER_INCOME',
        'S_SOURCE_OTHER_INCOME',
        'RELATION_REFERENCE',
        'RELATION_REF_DES',
        'REF_TAX_ID',
        'REF_TITLE',
        'REF_TITLE_OTHER',
        'REF_FIRSTNAME',
        'REF_LASTNAME',
        'REF_BIRTHDAY',
        'REF_AGE',
        'REF_OCCUPATION',
        'REF_OFFICE_NAME',
        'REF_BUSINESS_SIZE',
        'REF_OFFICE_POSITION',
        'REF_OFFICE_LEVEL',
        'REF_OFFICE_YEAR',
        'REF_MAIN_INCOME',
        'REF_EXPENSE',
        'REF_OTHER_INCOME',
        'REF_SOURCE_OTHER_INCOME',
        'REF_PHONE',
        'REF_EMAIL',
        'REF_LINEID',
        'REF_FACEBOOK',
        'CARD_CODE_FILE',
        'CARD_CODE_FILE_SECOND',
        'STUDENT_CARD_FILE',
        'STUDENT_CARD_FILE_SECOND',
        'FACE_PERSON',
        'FACE_PERSON_SECOND',
        'CONSENT_FILE',
        'STATEMENT_FILE_THIRD',
        'STATEMENT_FILE_SECOND',
        'STATEMENT_FILE',
        'BANK_STATE_FILE_FOURTH',
        'BANK_STATE_FILE_THIRD',
        'BANK_STATE_FILE_SECOND',
        'BANK_STATE_FILE',
        'SLIP_FILE',
        'ADR_MAP',
        'DS_FILE',
        'DS_IMAGE',
        'DS_PDPA',
        'DS_MKR',
        'DS_GUAR',
        'CONFIRM_INFOR',
        'CONFIRM_PDPA',
        'CREATE_DATE',
        'UPDATE_DATE',
        'NAME_MAKE',
        'PHONE_SECOND',
        'REF_PHONE_WORK',
        'REF_PHONE_SECOND',
        'Disease_ID',
        'Narcotic_ID',
        'APPROVE_CUSTOMER',
        'FINANCIAL_AMOUNT',
        'FINANCIAL_AMOUNT_TRUE',
        'CREDIT_CARD',
        'INSTITUTION_BANK',
        'INSTITUTION_BANK_AMOUNT',
        'TYPE_LOAN_HP',
        'Acknowledge_ID',
        'Balloon_Type',
        'TRADE_IN_TYPE',
        'RELATION_REFERENCE_2',
        'RELATION_REF_DES_2',
        'REF_TAX_ID_2',
        'REF_TITLE_2',
        'REF_TITLE_OTHER_2',
        'REF_FIRSTNAME_2',
        'REF_LASTNAME_2',
        'REF_BIRTHDAY_2',
        'REF_AGE_2',
        'REF_OCCUPATION_2',
        'REF_PHONE_2',
        'REF_PHONE_SECCOND_2',
    ];
}
