<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class QUOTATION extends Model
{
    protected $table = 'QUOTATION';

    public $timestamps = false;

    use HasFactory;

    protected $primaryKey = 'QUOTATION_ID';

    protected $fillable = [
        'QUOTATION_ID',
        'QT_DATE',
        'DATE_END',
        'STATUS_ID',
        'APPROVE_CODE',
        'BRANCH_TYPE',
        'BRANCH_ID',
        'BRANCH_AD',
        'TAX_ID',
        'CUSTOMER_NAME',
        'OCCUPATION_ID',
        'UNIVERSITY_ID',
        'CAMPUS_ID',
        'FACULTY_ID',
        'FLAG_GUARANTOR',
        'PRODUCT_TYPE',
        'PRODUCT_CATEGORY',
        'PRODUCT_BAND',
        'PRODUCT_SERIES',
        'PRODUCT_SUB_SERIES',
        'PRODUCT_COLOR',
        'REMARK',
        'PROD_PRICE',
        'PROD_VAT',
        'PROD_SUM_PRICE',
        'DOWN_PERCENT',
        'DOWN_AMT',
        'DOWN_VAT',
        'DOWN_SUM_AMT',
        'HP_AMT',
        'HP_INVEST_AMT',
        'INTEREST_FLAT',
        'INTEREST_EFFECTIVE',
        'INSTALL_NUM',
        'INTEREST_TOTAL',
        'INTEREST_VAT',
        'INTEREST_AMT',
        'HP_SUM',
        'INSTALL_NUM_FINAL',
        'INSTALL_AMT',
        'INSTALL_AMT_FINAL',
        'INSTALL_VAT',
        'INSTALL_VAT_FINAL',
        'INSTALL_SUM',
        'INSTALL_SUM_FINAL',
        'CREDIT_LIMIT',
        'HP_VAT_SUM',
        'PAY_DOWN_TYPE',
        'DESCRIPTION',
        'ACS_ID',
        'ACS_DES',
        'ACS_PRICE',
        'ACS_VAT',
        'ACS_SUM',
        'INSURE_ID',
        'INSURE_DES',
        'INSURE_SUM',
        'INSURE_VAT',
        'INSURE_TOTAL',
        'PROD_TOTAL',
        'PROD_TOTAL_VAT',
        'PROD_TOTAL_AMT',
        'Tradein_AMT',
        'ADDR_PROS_KYC',
        'DUEDATE_KYC',
        'PERIOD_KYC',
        'Addr_KYC_ID',
        'Delivery_ID',
        'CREATE_DATE',
        'UPDATE_DATE',
        'NAME_MAKE',
        'DEFAULT_DOWN_PERCENT',
        'Icare_Des',
        'Icare_Percent',
        'Icare_Price',
        'DOWN_SUM_VAT',
        'DOWN_SUM_TOTAL',
        'DOWN_PAY_AMT',
        'AMT_PERCENT',
        'TYPE_LOAN_HP',
        'FEE_TOTAL_AMT',
        'FEE_TOTAL',
        'FEE_VAT',
        'Balloon_Type',
        'TRADE_IN_TYPE',
        'INSTALL_NUM_BALLOON',
        'TRADE_IN_INSTALL',
        'PACKAGE_ID',
        'PACKAGE_AMT',
        'PACKAGE_VAT',
        'PACKAGE_SUM_AMT',
        'DISCOUNT_AMT',
        'DISCOUNT_VAT',
        'DISCOUNT_SUM_AMT',
        'TRADE_IN_DISCOUNT_AMT',
        'TRADE_IN_DISCOUNT_VAT',
        'TRADE_IN_DISCOUNT_SUM_AMT',
        'UTM_CODE',
    ];
}
